# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='zipcode',
            field=models.CharField(default='92660', max_length=120),
        ),
    ]
